version: '3.8'

services:
  api:
    build: ./api
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - sqlite_data:/app/data 

  frontend:
    build: ./frontend
    # коли контейнер стартує, він одразу збере білд
    command: sh -c "npm run build"
    volumes:
      - frontend_build:/app/dist
    networks:
      - app-network

  nginx:
    build: ./nginx
    volumes:
      - frontend_build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    networks:
      - app-network

volumes:
  sqlite_data:
  frontend_build:

networks:
  app-network:
    driver: bridge
