version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://backend:8000

networks:
  app-network:
    driver: bridge
