version: '3.8'

services:
  api:
    build: ./api
    image: api:latest
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - sqlite_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      # конфіг nginx, щоб він підтримував http+https+acme challenge
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      # сертифікати
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      # webroot для ACME challenge
      - ./frontend/public:/var/www/certbot

  console:
    build: ./console
    image: console:latest
    stdin_open: true
    tty: true
    volumes:
      - ./console:/app
    networks:
      - app-network
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./frontend/public:/var/www/certbot

  certbot-renew:
    image: certbot/certbot
    entrypoint: sh -c "while :; do certbot renew; sleep 12h; done"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

volumes:
  sqlite_data:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
