version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - sqlite_data:/app/data 

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://api:8000

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge
