version: '3.8'

services:
  api:
    build: ./api
    image: api:latest
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - sqlite_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - app-network

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge
