version: '3.8'

services:
  api:
    build: ./api
    image: api:latest
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - sqlite_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      
  console:
    build: ./console
    image: console:latest
    stdin_open: true   
    tty: true          
    volumes:
      - ./console:/app
    networks:
      - app-network
    depends_on:
      - api

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge
