version: '3.8'

services:
  api:
    build: ./api
    image: api:latest
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - sqlite_data:/app/data

  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/public:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt


  console:
    build: ./console
    image: console:latest
    stdin_open: true
    tty: true
    volumes:
      - ./console:/app
    networks:
      - app-network
    depends_on:
      - api


  certbot:
    image: certbot/certbot
    depends_on:
      - frontend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./frontend/public:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot -d remoteshellsoftcom.duckdns.org --agree-tos --email your-email@example.com --non-interactive

  certbot-renew:
    image: certbot/certbot
    entrypoint: sh -c "while :; do certbot renew; sleep 12h; done"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

volumes:
  sqlite_data:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
