name: Build and Push

on:
  workflow_dispatch:

jobs:
  build_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        run: |
          docker build -t $DOCKERHUB_USERNAME/api:$IMAGE_TAG ./api
          docker push $DOCKERHUB_USERNAME/api:$IMAGE_TAG

      - name: Build and push Frontend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/frontend:$IMAGE_TAG ./frontend
          docker push $DOCKERHUB_USERNAME/frontend:$IMAGE_TAG

      - name: Build and push Console image
        run: |
          docker build -t $DOCKERHUB_USERNAME/console:$IMAGE_TAG ./console
          docker push $DOCKERHUB_USERNAME/console:$IMAGE_TAG
