name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      COMMIT_SHA: ${{ github.sha }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build all Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Tag and Push API image
        run: |
          docker tag api:latest $DOCKERHUB_USERNAME/api:latest
          docker push $DOCKERHUB_USERNAME/api:latest

      - name: Tag and Push Frontend image
        run: |
          docker tag frontend:latest $DOCKERHUB_USERNAME/frontend:latest
          docker push $DOCKERHUB_USERNAME/frontend:latest

      - name: Tag and Push Nginx image
        run: |
          docker tag nginx:latest $DOCKERHUB_USERNAME/nginx:latest
          docker push $DOCKERHUB_USERNAME/nginx:latest

      - name: Tag and Push Console image
        run: |
          docker tag console:latest $DOCKERHUB_USERNAME/console:latest
          docker push $DOCKERHUB_USERNAME/console:latest
