#Build and push docker image to docker hub.yml
name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      COMMIT_SHA: ${{ github.sha }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_TAG: latest
      API_IMAGE: api
      FRONTEND_IMAGE: frontend
      NGINX_IMAGE: nginx
      CONSOLE_IMAGE: console

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and push Docker images
        run: |
          # API
          docker build -t $DOCKERHUB_USERNAME/$API_IMAGE:$IMAGE_TAG ./api
          docker push $DOCKERHUB_USERNAME/$API_IMAGE:$IMAGE_TAG

          # Frontend
          docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:$IMAGE_TAG ./frontend
          docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:$IMAGE_TAG

          # Nginx
          docker build -t $DOCKERHUB_USERNAME/$NGINX_IMAGE:$IMAGE_TAG ./nginx
          docker push $DOCKERHUB_USERNAME/$NGINX_IMAGE:$IMAGE_TAG

          # Console
          docker build -t $DOCKERHUB_USERNAME/$CONSOLE_IMAGE:$IMAGE_TAG ./console
          docker push $DOCKERHUB_USERNAME/$CONSOLE_IMAGE:$IMAGE_TAG
